# Generated by Django 4.0.4 on 2022-08-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_staff_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_code',
            field=models.CharField(default='', max_length=200),
        ),
    ]
