# Generated by Django 4.0.4 on 2022-07-07 09:07

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "added",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("url", embed_video.fields.EmbedVideoField()),
            ],
            options={
                "ordering": ["-added"],
            },
        ),
    ]
